project:
  title: "Home"
  type: website

website:
  navbar:
    right:
      - icon: github
        href: https://github.com/gessulat
      - text: Resume
        href: https://resume.gessulat.io
format:
  html:
    grid:
      margin-width: 800px
      body-width: 800px
    css: styles.css
    mainfont: "IM Fell DW Pica"
    main-color: #008080
    smooth-scroll: true



