project:
  title: "Home"
  type: website

website:
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gessulat
format:
  html:
    theme: 
      - custom.scss
    css: styles.css
    mainfont: "IM Fell DW Pica"



